IF OBJECT_ID('USP_INSERT_USER', 'P') IS NOT NULL
    DROP PROCEDURE USP_INSERT_USER
GO

CREATE PROCEDURE USP_INSERT_USER   
    @USERNAME nvarchar(100),   
    @EMAIL nvarchar(200),
    @PASSWORD NVARCHAR(255),  
    @DISPLAY_NAME NVARCHAR(255) 
AS   

    INSERT INTO USERS
        (USERNAME, EMAIL, [PASSWORD], DISPLAY_NAME)
    VALUES
        (@USERNAME, @EMAIL, @PASSWORD, @DISPLAY_NAME)

    SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]; 

GO  