IF OBJECT_ID('USP_UPDATE_USER', 'P') IS NOT NULL
    DROP PROCEDURE USP_UPDATE_USER
GO

CREATE PROCEDURE USP_UPDATE_USER
	@ID INT,
	@USERNAME NVARCHAR(100),   
    @EMAIL NVARCHAR(200),
    @PASSWORD NVARCHAR(255),  
    @DISPLAY_NAME NVARCHAR(255) 
AS   
	UPDATE USERS
	SET
		USERNAME=@USERNAME,
		EMAIL=@EMAIL,
		[PASSWORD]=@PASSWORD,
		DISPLAY_NAME=@DISPLAY_NAME
	WHERE
		ID=@ID
GO  