IF OBJECT_ID('USP_SELECT_USER', 'P') IS NOT NULL
    DROP PROCEDURE USP_SELECT_USER
GO

CREATE PROCEDURE USP_SELECT_USER
	@ID INT = NULL,
    @SHOW_INACTIVES TINYINT = 1  
AS   
	SELECT
		ID, USERNAME, EMAIL, [PASSWORD], DISPLAY_NAME, ACTIVE
	FROM USERS U
	WHERE
		(@ID IS NULL OR ID = @ID)
		AND (@SHOW_INACTIVES = 1 OR ACTIVE = 1)
GO  