IF OBJECT_ID('USERS', 'U') IS NULL 
BEGIN
    CREATE TABLE USERS (
        ID INT PRIMARY KEY IDENTITY(1,1),
        USERNAME NVARCHAR(200) NOT NULL UNIQUE,
        EMAIL NVARCHAR(200) NOT NULL UNIQUE,
        [PASSWORD] NVARCHAR(255) NOT NULL,
        DISPLAY_NAME NVARCHAR(255) NOT NULL,
		ACTIVE TINYINT DEFAULT 1,
        CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
        UPDATE_DATE DATETIME
    );
END

IF OBJECT_ID('BOOKS', 'U') IS NULL 
BEGIN
    CREATE TABLE BOOKS(
        ID INT PRIMARY KEY IDENTITY(1,1),
        AUTHOR INT NOT NULL,
        TITLE NVARCHAR(200) NOT NULL,
        SUMMARY NVARCHAR(255),
        FINISHED TINYINT DEFAULT 0  NOT NULL,
		ACTIVE TINYINT DEFAULT 1,
        CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
        UPDATE_DATE DATETIME,
        Foreign KEY(AUTHOR) references USERS(ID)
    );
END

IF OBJECT_ID('FAVORITES', 'U') IS NULL
BEGIN
    CREATE TABLE FAVORITES (
        USER_ID INT,
        BOOK INT,
		ACTIVE TINYINT DEFAULT 1,
        PRIMARY KEY(USER_ID, BOOK),
        Foreign KEY (USER_ID) references USERS(ID),
        Foreign KEY (BOOK) references BOOKS(ID)
        ON DELETE CASCADE
    );
END

IF OBJECT_ID('CHAPTERS', 'U') IS NULL 
BEGIN
    CREATE TABLE CHAPTERS(
        ID INT PRIMARY KEY IDENTITY(1,1),
        BOOK INT NOT NULL,
        DESCRIPTION NVARCHAR(500),
        ORDER_NUM INT,
        CONTENT NVARCHAR(4000) NOT NULL,
        TITLE VARCHAR(100) NOT NULL,
		ACTIVE TINYINT DEFAULT 1,
        CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
        Foreign KEY(BOOK) references BOOKS(ID)
        ON DELETE CASCADE
    );
END

IF OBJECT_ID('COMMENTS', 'U') IS NULL 
BEGIN
    CREATE TABLE COMMENTS(
        ID INT PRIMARY KEY IDENTITY(1,1),
        CONTENT NVARCHAR(400),
        USER_ID INT NOT NULL,
        CHAPTER INT NOT NULL,
        ACTIVE TINYINT DEFAULT 1,
        CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
        Foreign KEY(USER_ID) references USERS(ID),
        Foreign KEY(CHAPTER) references CHAPTERS(ID)
    );
END